### ISSUE TITLE
node fuckIndex.js throws error

### ISSUE THREAD

**Issue by TheBearodactyl** [nashwik/nekos.life_downloader#1]
500
/home/emi/.junk/repos/nekos.life_downloader/fuckIndex.js:67
    const sfw = response.data.data.response.endpoints.images[0].categories.sfw;
                         ^

TypeError: Cannot read properties of undefined (reading 'data')
    at getApiList (/home/emi/.junk/repos/nekos.life_downloader/fuckIndex.js:67:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getUserNeed (/home/emi/.junk/repos/nekos.life_downloader/fuckIndex.js:39:21)
    at async main (/home/emi/.junk/repos/nekos.life_downloader/fuckIndex.js:26:18)

Node.js v20.2.0

**Comment by nashwik** [comment]
endpoint is down
